### ISSUE TITLE
[Feature Request] Option for HTTP / HTTPS Protocol - MailcoachApiTransport.php  -- config/mail.php

### ISSUE THREAD

**Issue by ibrainventures** [spatie/laravel-mailcoach-mailer#12]
Dear Spatie,

thank you for this usefull Package.

Inside the MailcoachApiTransport.php there is the Protocol Standard Hardwired to https://

![grafik](https://github.com/spatie/laravel-mailcoach-mailer/assets/8803626/2523a32a-3303-4ee8-8ba7-3f30bed2b978)

Inside our Usecase / NOC we are using mostly non-https services and upstream those to SSL headed Nginx proxy.
So the internal Serices / API Communication (like the setup for redis and mysql server) are done by direct or local
http / service protocols.

If there would a option to config this https (or in our case http) setting by config this would very helpful
Thank you and best regards
J.

 (Cant open a feature request inside this Issue Git .. there comes 404 :-/ )

**Comment by freekmurze** [comment]
Feel free to create a PR. You need to have a Mailcoach license to be able to view the spatie/laravel-mailcoach repo (If you buy a license, you'll get an automatic invite to the repo).

**Comment by plompd** [comment]
From this code I assume I can use the Mailcoach Mailer also with a standalone version of Mailcoach?
