### ISSUE TITLE
How can I send fake transactional emails?

### ISSUE THREAD

**Issue by ragulka** [spatie/laravel-mailcoach-mailer#22]
Mailcoach transactional API has a [`fake` option](https://www.mailcoach.app/api-documentation/endpoints/transactional-mails) to basically [trap the emails in mailcoach](https://www.mailcoach.app/features/fake-transactional-mails), but how can we use it in Laravel when sending emails?

**Comment by francoism90** [comment]
@ragulka Did you ever found an answer?

I have the same question.

**Comment by francoism90** [comment]
@freekmurze You didn't merged this one yet: https://github.com/spatie/mailcoach-mailer/pull/19

Just to let you know, because it's a dep of that one. :)
